
all:
	cd design; make
	cd schedule; make
	cd requirements; make
	cd testing; make
	cd concept; make
	cd datasheet; make
	cd technology-roadmap; make
	cd poster-board; make

clean:
	cd concept; make clean
	cd datasheet; make clean
	cd design; make clean
	cd poster-board; make clean
	cd requirements; make clean
	cd schedule; make clean
	cd technology-roadmap; make clean
	cd testing; make clean
