#!/bin/bash
### BEGIN INIT INFO
# Provides:          sprinklerpi-waterd
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Web based sprinkler controller.
# Description:       Sprinkler controller for turning on sprinkler valves
#                    manually or as part of a schedule.
#
#                    http://github.com/jmahler/sprinklerpi
### END INIT INFO

# Author: Jeremiah Mahler <jmmahler@gmail.com>

DESC="sprinklerpi water daemon"
NAME="spkpi-waterd"

DIR=/home/sprinklerpi/sprinklerpi/www/sprinklerpi
BIN=/home/sprinklerpi/sprinklerpi/bin
USER=sprinklerpi
GROUP=sprinklerpi
DEV="/dev/null"

. /lib/lsb/init-functions

if [ -f /etc/default/sprinklerpi ] ; then
	. /etc/default/sprinklerpi
fi

DAEMON="$BIN/spkpi-waterd"
PIDFILE="$DIR/var/run/pid/$NAME.pid"

if ! test -x $DAEMON; then
	log_failure_msg "Daemon is not executable."
	exit 1
fi

do_start() {
	log_daemon_msg "Starting $DESC" "$NAME";
	if start-stop-daemon --start --make-pidfile --pidfile $PIDFILE --background --exec "/usr/bin/perl" --startas $DAEMON --chuid $USER:$GROUP -- $DIR ; then
		log_end_msg 0
	else
		log_end_msg 1
		exit 1
	fi
}

do_stop() {
	log_daemon_msg "Stopping $DESC" "$NAME";
	start-stop-daemon --stop --pidfile $PIDFILE
	status=$?
	log_end_msg $status
}

case "$1" in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	restart)
		log_action_msg "Restarting $NAME" "$NAME";
		do_stop
		do_start
		;;
	*)
		echo "Usage: sprinklerpi-waterd [start|stop|restart]" >&2
		exit 3
		;;
esac

exit 0
