#!/bin/bash
### BEGIN INIT INFO
# Provides:          sprinklerpi-server
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Web based sprinkler controller.
# Description:       Sprinkler controller for turning on sprinkler valves
#                    manually or as part of a schedule.
#
#                    http://github.com/jmahler/sprinklerpi
### END INIT INFO

# Author: Jeremiah Mahler <jmmahler@gmail.com>

DESC="sprinklerpi-server daemon"
NAME="sprinklerpi-server"

DIR=/home/sprinklerpi/sprinklerpi/www/sprinklerpi
BIN=/home/sprinklerpi/sprinklerpi/bin
PIDIR=/home/sprinklerpi/sprinklerpi/var/run/sprinklerpi
USER=sprinklerpi
GROUP=sprinklerpi
PORT=5000

. /lib/lsb/init-functions

if [ -f /etc/default/sprinklerpi ] ; then
	. /etc/default/sprinklerpi
fi

DAEMON="$BIN/spkpi-waterd-server"
PIDFILE="$PIDIR/$NAME.pid"

if ! test -x $DAEMON; then
	log_failure_msg "Daemon is not executable."
	exit 1
fi

do_start() {
	log_daemon_msg "Starting $NAME" "$NAME";
	if start-stop-daemon --start --make-pidfile --pidfile $PIDFILE --background --exec $DAEMON --chuid $USER:$GROUP -- $PORT $DIR; then
		log_end_msg 0
	else
		log_end_msg 1
		exit 1
	fi
}

do_stop() {
	log_daemon_msg "Stopping $NAME" "$NAME";
	start-stop-daemon --stop --pidfile $PIDFILE 
	status=$?
	log_end_msg $status
}

case "$1" in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	restart)
		log_action_msg "Restarting $NAME" "$NAME";
		do_stop
		do_start
		;;
	*)
		echo "Usage: sprinklerpi [start|stop|restart]" >&2
		exit 3
		;;
esac

exit 0
