#!/bin/bash
### BEGIN INIT INFO
# Provides:          sprinklerpi
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Web based sprinkler controller.
# Description:       Sprinkler controller for turning on sprinkler valves
#                    manually or as part of a schedule.
#
#                    http://github.com/jmahler/sprinklerpi
### END INIT INFO

# Author: Jeremiah Mahler <jmmahler@gmail.com>

DESC="sprinklerpi daemon"
NAME=sprinklerpi

DIR=/home/jeri/sprinklerpi/www/sprinklerpi
BIN=/home/jeri/sprinklerpi/bin
DAEMONS=("spkpi-waterd" "spkpi-queued" "spkpi-scheduled" "spkpi-demo")
USER=jeri
GROUP=jeri

. /lib/lsb/init-functions

case "$1" in
	start)
		for DAEMON in ${DAEMONS[@]}; do
			log_daemon_msg "Starting $DAEMON" "$DAEMON";
			start-stop-daemon --start --make-pidfile --pidfile $DIR/var/run/pid/$DAEMON.pid --background --exec $BIN/$DAEMON --chuid $USER:$GROUP -- $DIR
			status=$?
			log_end_msg $status
		done

		;;
	stop)
		for DAEMON in ${DAEMONS[@]}; do
			log_daemon_msg "Stopping $DAEMON" "$DAEMON";
			start-stop-daemon --stop --pidfile $DIR/var/run/pid/$DAEMON.pid
			status=$?
			log_end_msg $status
		done

		;;
	*)
		echo "Usage: sprinklerpi [start|stop]" >&2
		exit 3
		;;
esac

exit 0
