#!/bin/bash
### BEGIN INIT INFO
# Provides:          sprinklerpi-server
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Web based sprinkler controller.
# Description:       Sprinkler controller for turning on sprinkler valves
#                    manually or as part of a schedule.
#
#                    http://github.com/jmahler/sprinklerpi
### END INIT INFO

# Author: Jeremiah Mahler <jmmahler@gmail.com>

DESC="sprinklerpi-server daemon"
NAME=sprinklerpi-server

DIR=/home/sprinklerpi/sprinklerpi/www/sprinklerpi
BIN=/home/sprinklerpi/sprinklerpi/bin
USER=sprinklerpi
GROUP=sprinklerpi
export BIN

DAEMON="spkpi-waterd-server-wrapper"

if [ -f /etc/default/sprinklerpi ] ; then
	. /etc/default/sprinklerpi
fi

. /lib/lsb/init-functions

case "$1" in
	start)
		log_daemon_msg "Starting $DAEMON" "$DAEMON";
		start-stop-daemon --start --make-pidfile --pidfile $DIR/var/run/pid/$DAEMON.pid --background --exec $BIN/$DAEMON --chuid $USER:$GROUP -- $DIR
		status=$?
		log_end_msg $status

		;;
	stop)
		log_daemon_msg "Stopping $DAEMON" "$DAEMON";
		start-stop-daemon --stop --pidfile $DIR/var/run/pid/$DAEMON.pid
		status=$?
		log_end_msg $status

		;;
	*)
		echo "Usage: sprinklerpi [start|stop]" >&2
		exit 3
		;;
esac

exit 0
